docs: update docs/4_ImprementTokenDapps.md for Hardhat
nakajo2011/eth-dapp-sample pull request #5
Opened 2024-09-04 09:39 UTC by r-nakashio

### 変更点
* Truffle関係の記述をHardhatに対応した記述に変更
* 見出しの変更
* 画像の一部追加

### 動作確認
OS: WSL(Ubuntu 22.04)上で確認済み

### 参考資料
* https://docs.web3js.org/guides/hardhat_tutorial/

2024-09-05 07:35 UTC, nakajo2011 commented on docs/4_ImplementTokenDapps.md
> +まず最初に、`src/contracts`ディレクトリを作成し、その中にhardhatで生成された`../contracts/artifacts/contracts/MyToken.sol/MyToken.json`をコピーします。
artifacts/@openzeppelin以下にERC20のjsonファイルがあると思うのでそちらをコピーするように修正お願いします。
MyToken.jsonでも動作はするのですが説明の趣旨から少し意味が離れてしまうので。
原著の趣旨を優先するならERC20.jsonファイルをコピーする方が良いです。

2024-09-05 07:36 UTC, nakajo2011 requested changes
MyToken.json部分をERC20.jsonになるよう修正お願いします。

2024-09-05 08:19 UTC, r-nakashio commented on docs/4_ImplementTokenDapps.md
> +まず最初に、`src/contracts`ディレクトリを作成し、その中にhardhatで生成された`../contracts/artifacts/contracts/MyToken.sol/MyToken.json`をコピーします。
`packages/contracts/artifacts/@openzeppelin/contracts/token/ERC20/ERC20.sol/ERC20.json`をコピーするようにします！

2024-09-06 11:01 UTC, nakajo2011 approved these changes
LGTM!

2024-09-06 11:01 UTC, merged